[package]
name = "quickmark_linter"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
once_cell = "1.19"
regex = "1.0"
tree-sitter = "0.25.6"
tree-sitter-md = "0.3.2"

[features]
testing = []
