[package]
name = "quickmark_config"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
quickmark_linter = { path = "../quickmark_linter" }
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14" 