[linters.severity]
heading-increment = 'off'
heading-style = 'off'
ul-style = 'off'
list-indent = 'off'
no-trailing-spaces = 'off'
no-hard-tabs = 'off'
no-missing-space-atx = 'off'
no-multiple-space-atx = 'off'
no-multiple-space-closed-atx = 'off'
no-missing-space-closed-atx = 'off'
no-multiple-blanks = 'off'
line-length = 'off'
commands-show-output = 'off'
no-space-in-emphasis = 'off'
no-space-in-code = 'off'
no-space-in-links = 'off'
no-space-in-links-extended = 'off'
blanks-around-headings = 'off'
no-duplicate-heading = 'off'
single-h1 = 'off'
blanks-around-fences = 'off'
no-inline-html = 'off'
no-bare-urls = 'off'
fenced-code-language = 'off'
required-headings = 'off'
code-block-style = 'off'
code-fence-style = 'err'
link-fragments = 'off'
reference-links-images = 'off'
link-image-reference-definitions = 'off'

[linters.settings.code-fence-style]
style = 'consistent'