[linters.severity]
"line-length" = "err"
"heading-increment" = "off"
"heading-style" = "off"

[linters.settings.line-length]
line_length = 80
heading_line_length = 80
code_block_line_length = 80
code_blocks = true
headings = true
tables = true
strict = false
stern = true