[linters]

[linters.severity]
heading-increment = "off"
heading-style = "off"
ul-style = "off"
list-indent = "off"
trailing-spaces = "off"
no-hard-tabs = "off"
line-length = "off"
commands-show-output = "off"
no-space-in-emphasis = "off"
no-space-in-code = "off"
no-space-in-links = "off"
no-space-after-hash = "off"
blanks-around-headings = "off"
no-multiple-headings = "off"
single-h1 = "off"
blanks-around-fences = "off"
blanks-around-lists = "off"
no-inline-html = "off"
no-bare-urls = "off"
required-headings = "off"
link-fragments = "off"
reference-links-images = "off"
link-image-reference-definitions = "off"
no-reversed-links = "err"