[linters.severity]
# Disable all rules except MD036
"heading-increment" = "off"
"heading-style" = "off"
"ul-style" = "off"
"list-indent" = "off"
"no-trailing-spaces" = "off"
"no-hard-tabs" = "off"
"no-reversed-links" = "off"
"no-multiple-blanks" = "off"
"line-length" = "off"
"no-space-in-emphasis" = "off"
"no-space-in-code" = "off"
"no-space-in-links" = "off"
"blanks-around-headings" = "off"
"heading-start-left" = "off"
"no-duplicate-heading" = "off"
"single-h1" = "off"
"no-trailing-punctuation" = "off"
"no-multiple-space-blockquote" = "off"
"no-blanks-blockquote" = "off"
"ol-prefix" = "off"
"list-marker-space" = "off"
"blanks-around-fences" = "off"
"blanks-around-lists" = "off"
"no-inline-html" = "off"
"no-bare-urls" = "off"
"hr-style" = "off"
"no-emphasis-as-heading" = "err"
"fenced-code-language" = "off"
"required-headings" = "off"
"code-block-style" = "off"
"code-fence-style" = "off"
"link-fragments" = "off"
"reference-links-images" = "off"
"link-image-reference-definitions" = "off"

[linters.settings.no-emphasis-as-heading]
# Custom punctuation - only period and comma allowed
punctuation = ".,"