# Configuration for testing MD027 only

[linters.severity]
"heading-increment" = "off"
"heading-style" = "off"
"ul-style" = "off"
"list-indent" = "off"
"no-trailing-spaces" = "off" 
"no-hard-tabs" = "off"
"no-reversed-links" = "off"
"no-duplicate-heading" = "off"
"line-length" = "off"
"commands-show-output" = "off"
"no-space-in-emphasis" = "off"
"no-space-in-code" = "off"
"no-space-in-links" = "off"
"blanks-around-fences" = "off"
"blanks-around-headings" = "off"
"heading-start-left" = "off"
"single-title" = "off"
"no-trailing-punctuation" = "off"
"no-multiple-space-blockquote" = "err"
"no-blanks-blockquote" = "off"
"ol-prefix" = "off"
"no-inline-html" = "off"
"no-bare-urls" = "off"
"fenced-code-language" = "off"
"first-line-heading" = "off"
"required-headings" = "off"
"code-block-style" = "off"
"code-fence-style" = "off"
"link-fragments" = "off"
"reference-links-images" = "off"
"link-image-reference-definitions" = "off"

[linters.settings.no-multiple-space-blockquote]
list_items = true