[linters.severity]
descriptive-link-text = 'err'

# All other rules off
heading-increment = 'off'
heading-style = 'off'
ul-style = 'off'
list-indent = 'off'
no-trailing-spaces = 'off'
no-hard-tabs = 'off'
no-missing-space-atx = 'off'
no-multiple-blanks = 'off'
line-length = 'off'
no-inline-html = 'off'
no-duplicate-heading = 'off'
single-h1 = 'off'
no-trailing-punctuation = 'off'
no-multiple-space-atx = 'off'
no-multiple-space-closed-atx = 'off'
no-missing-space-closed-atx = 'off'
heading-start-left = 'off'
blanks-around-headings = 'off'
no-multiple-space-blockquote = 'off'
no-blanks-blockquote = 'off'
list-marker-space = 'off'
blanks-around-fences = 'off'
blanks-around-lists = 'off'
hr-style = 'off'
no-emphasis-as-heading = 'off'
no-space-in-emphasis = 'off'
no-space-in-code = 'off'
no-space-in-links = 'off'
fenced-code-language = 'off'
first-line-heading = 'off'
no-empty-links = 'off'
required-headings = 'off'
no-alt-text = 'off'
code-block-style = 'off'
single-trailing-newline = 'off'
code-fence-style = 'off'
emphasis-style = 'off'
strong-style = 'off'
link-fragments = 'off'
reference-links-images = 'off'
link-image-reference-definitions = 'off'
link-image-style = 'off'
table-pipe-style = 'off'
table-column-count = 'off'
proper-names = 'off'

[linters.settings.descriptive-link-text]
prohibited_texts = ["read more", "voir plus", "learn more", "continue"]