[linters.severity]
# Enable only MD028 for testing
"no-blanks-blockquote" = "err"

# Disable all other rules
"heading-increment" = "off"
"heading-style" = "off"
"ul-style" = "off"
"ul-indent" = "off"
"list-indent" = "off"
"trailing-spaces" = "off"
"hard-tabs" = "off"
"reversed-links" = "off"
"line-length" = "off"
"commands-show-output" = "off"
"no-space-in-emphasis" = "off"
"no-space-in-code" = "off"
"no-space-in-links" = "off"
"no-collapsed-spaces" = "off"
"headings-blanks" = "off"
"no-duplicate-heading" = "off"
"single-h1" = "off"
"no-trailing-punctuation" = "off"
"no-multiple-space-blockquote" = "off"
"blanks-around-fences" = "off"
"blanks-around-lists" = "off"
"no-inline-html" = "off"
"bare-url" = "off"
"fenced-code-language" = "off"
"required-headings" = "off"
"code-block-style" = "off"
"code-fence-style" = "off"
"link-fragments" = "off"
"reference-links-images" = "off"
"link-image-reference-definitions" = "off"